services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: live_art_dev
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432